### ISSUE TITLE
uninstall confirmation cannot be skipped

### ISSUE THREAD

**Issue by aurkaxi** [ibonn/python_avatars#4]
`pa.uninstall_part(pa.ClothingType.SUIT, confirm=True/False)`
for both case it asks user confirmation.

**Comment by ibonn** [comment]
Hello!

I cannot fix this right now (I don't have enough time), but I will tackle it as soon as possible

Thanks for your feedback!

**Comment by ibonn** [comment]
Should be fixed by cadeb2b7b5388439f50eeda94a9dd3e57e00c97e
