### ISSUE TITLE
facial_hair_color always white when using Avatar.random and passing some value like 'facial_hair_color': '#4a312c'

### ISSUE THREAD

**Issue by frafart** [ibonn/python_avatars#6]
**Describe the bug**
When generating a new random avatar, if you use facial_hair_color it always generate white, for instance: when using Avatar.random and passing some value like 'facial_hair_color': '#4a312c'

**To Reproduce**
Generate a random Avatar with this json:

{'style': 'transparent', 'top': 'pixie', 'hat_color': '#25557C', 'eyebrows': 'angry_natural', 'eyes': 'side', 'nose': 'default', 'mouth': 'disbelief', 'facial_hair': 'wick_beard', 'skin_color': '#ae5d29', 'hair_color': '#d6b370', 'facial_hair_color': '#4a312c', 'accessory': 'kurt', 'clothing': 'shirt_crew_neck', 'clothing_color': '#929598', 'shirt_graphic': 'resist', 'shirt_text': 'None', 'title': 'None'}

**Expected behavior**
It would generate the avatar with the specified color.

**Comment by ibonn** [comment]
I am not able to reproduce the bug. I generated the avatar you described 

```python
import python_avatars as pa

avatar = pa.Avatar(
    style=pa.AvatarStyle.TRANSPARENT,
    top=pa.HairType.PIXIE,
    hat_color='#25557C',
    eyebrows=pa.EyebrowType.ANGRY_NATURAL,
    eyes=pa.EyeType.SIDE,
    nose=pa.NoseType.DEFAULT,
    mouth=pa.MouthType.DISBELIEF,
    facial_hair=pa.FacialHairType.WICK_BEARD,
    skin_color='#ae5d29',
    hair_color='#d6b370',
    facial_hair_color='#4a312c',
    accessory=pa.AccessoryType.KURT,
    clothing=pa.ClothingType.SHIRT_CREW_NECK,
    clothing_color='#929598',
    shirt_graphic=pa.ClothingGraphic.RESIST,
    shirt_text=None,
    title=None,
)
```
which outputs an avatar with the requested facial hair color
![avatar](https://github.com/user-attachments/assets/1f2be9f8-5384-43af-a74f-600f981ab3b1)

I tried with `Avatar.random` too, but i am still unable to reproduce it:

```python
pa.Avatar.random(
    facial_hair_color='#ff0000',
)
```
![avatar](https://github.com/user-attachments/assets/4fbe267f-03e0-47c7-9d34-86e2f3c9c934)

Can you give more context? maybe one of the base svgs is missing something

**Comment by frafart** [comment]
Hi @ibonn first of all, thank you for reviewing this issue, I really appreciate that.

Second, something should being updated since I've reported the issue, that now it's working as expected, I'm also unable to reproduce the issue on my environtment, so... I think we can close the issue as solved.  :)

Bests!!
